[package]
name = "game"
version = "0.1.0"
edition = "2021"

[dependencies]
common.path = "../common"
engine.path = "../engine"
env_logger = "0.11.5"
glam.workspace = true
hecs.workspace = true
log.workspace = true
rand = "0.8.5"
renderer.path = "../renderer"
